version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgresvolume:/var/lib/postgresql/data

  redis:
    image: redis

  celery:
    build:
      context: ./backend
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    command: celery -A app.worker.celery worker --loglevel=info

volumes:
  postgresvolume:


